services:
  - redis-server

git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - go version
  - go env

script:
  # Build
  - go build github.com/philippgille/gokv/...
  # Test and generate code coverage report
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic github.com/philippgille/gokv/...

after_success:
  # Upload coverage data to codecov.io
  - bash <(curl -s https://codecov.io/bash)
