# Sudo is required for running Docker
sudo: required

services:
  # Docker is required for running some services that aren't provided by Travis CI, e.g. Consul
  - docker
  - redis-server
  - mongodb
  - memcached
  - mysql

git:
  depth: 1

language: go

go:
  - "1.10"

before_install:
  - go version
  - go env

# Don't start Docker containers all at once. The Travis CI VM doesn't have enough memory for that.
# TODO: Implement a proper wait (e.g. with container health check) instead of sleeping for 10s
script:
  # Build
  - go build -v ./...
  # Test all packages that don't require a service
  - go test -v -race -coverprofile=coverage1.txt -covermode=atomic ./badgerdb ./bbolt ./bigcache ./freecache ./gomap ./leveldb ./syncmap
