# Sudo is required for running Docker
sudo: required

services:
  # Docker is required for running some services that aren't provided by Travis CI, e.g. Consul
  - docker
  - redis-server
  - mongodb
  - memcached
  - mysql

git:
  depth: 1

language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

before_install:
  - go version
  - go env

script:
  # Build
  - go build -v ./...
  # Test all packages that don't require a service
  - go test -v -race -count 10 -coverprofile=coverage1.txt -covermode=atomic ./badgerdb ./bbolt ./bigcache ./freecache ./gomap ./leveldb ./syncmap
  # Snip... (removed all other tests - only the above is relevant for BigCache)
